server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

camel:
  routes:
    number-to-words:
      name: direct:number-to-words
      id: numberToWordsId
    number-to-dollars:
      name: direct:number-to-dollars
      id: numberToDollarsId
